spring:
  application:
    name: gateway
  cloud:
    kubernetes:
      discovery:
        enabled: true
    gateway:
      routes:
        - id: backend-service
          uri: lb://backend-service
          predicates:
            - Path=/**
    loadbalancer:
      configurations: request-based-sticky-session
      sticky-session:
        add-service-instance-cookie: true
        instance-id-cookie-name: sc-lb-instance-id

management:
  endpoints:
    web:
      exposure:
        include: health
